@startuml Sequence
skinparam sequenceMessageAlign right
title "Sequence Diagram"
actor Creator
actor User
participant EventService
participant NotificationService

database db

Creator -> EventService : Create(string title, string description, string location, datetime time, int hours)
EventService -> db : CreateEventEntity(string title, string description, string location, datetime time, int hours, int createdById)
db --> EventService : ok
EventService --> Creator : ok
User -> EventService : AskToJoin(int eventId)
EventService -> db : CreateRequest(int eventId, int userId, int approvalStauts)
db --> EventService : ok
EventService --> Creator : ok
EventService -> NotificationService : NotifyCreator(int eventId)
NotificationService -> Creator: SendNotification(int eventId)

Creator -> EventService : Approve(int requestId)
EventService -> db : UpdateRequest(int requestId, int approvalStatus)
db --> EventService : ok
EventService -> db : UpdateEventQuota(int eventId)
db --> EventService : ok
EventService -> NotificationService : NotifyUser(int eventId)
NotificationService -> User: SendNotification(int eventId, int userId)


Creator -> Creator : Follow
Creator -> User : Follow
User -> Creator : Follow
User -> User : Follow

Creator -> Creator : Block
Creator -> User : Block
User -> Creator : Block
User -> User : Block
@enduml
